### ISSUE TITLE
Scrollview inside the content view?

### ISSUE THREAD

**Issue by patthehuman** [iDevelopper/PBPopupController#1]
I have a tableview inside of the content view and it doesnt scroll at the same time

**Comment by iDevelopper** [comment]
Can you elaborate please? Is your tableView in a UIViewController subclass and not in a UITableViewController? Is your tableview scroll? Do you mean that the content close before the table view is at top? Can you send here a video please?

**Comment by iDevelopper** [comment]
Ping
