### ISSUE TITLE
How to dismiss popup with my own custom button action

### ISSUE THREAD

**Issue by abdulKarim002** [iDevelopper/PBPopupController#10]
I tried with `self.popupContentViewController.closePopup(animated: true)`but it always comes nil,
I have used the same way how it was described in PBPopupLeakTest.zip file project u have shared on https://github.com/iDevelopper/PBPopupController/issues/3

**Comment by abdulKarim002** [comment]
didn't follow protocol so it was happing, not working with the help of https://github.com/LeoNatan/LNPopupController/issues/271

**Comment by iDevelopper** [comment]
In popupContentViewController:
```swift
    @IBAction func closeAction(_ sender: Any) {
        self.popupContainerViewController.closePopup(animated: true)
    }
```
