### ISSUE TITLE
SwiftUI support would be awesome!

### ISSUE THREAD

**Issue by samirsd** [iDevelopper/PBPopupController#11]

**Comment by iDevelopper** [comment]
Hello,

I don't know SwiftUI at all and I still wonder what would be the point of interest in regard of storyboards except maybe easier reading than a xml, checking a PR.

Do you have any idea what should be changed for this?

Pull requests are also welcome.

**Comment by samirsd** [comment]
I think the simplest approach for now would be to create a SwiftUI wrapper so that it can be dropped into a SwiftUI view like so : 

struct MyFloatingPlayerView: View {
    var body: some View {
            PBPopupView()
    }
}

**Comment by iDevelopper** [comment]
Hi @samirsd ,

Can you test the last version (3.3.0 with a SwiftUI wrapper).

Not yet documented but with examples, and not yet fully completed.

Thanks for your feedback.

**Comment by samirsd** [comment]
Hi, I just integrated it into my project and it works great so far! Works seamlessly with SwiftUI, thank you. The only bug I found is that the small player does not populate text and thumbnail on first load, only after tapping once does it populate. I’m running iOS 14.2 on iPhone 11 pro.

**Comment by iDevelopper** [comment]
Can you upload a sample project here?

**Comment by samirsd** [comment]
will do
