### ISSUE TITLE
Frame is not accurate after hiding tab bar 

### ISSUE THREAD

**Issue by PramodShukla10** [iDevelopper/PBPopupController#13]
while hide tab bar - PBPopView frame not align to bottom of superview

**Comment by iDevelopper** [comment]
Direct manipulation of tab bars is not supported (and discouraged by Apple). It’s not a good idea touching the tab bar like that.

**Comment by iDevelopper** [comment]
https://developer.apple.com/documentation/uikit/uitabbarcontroller/1621174-tabbar?language=objc

> You should never attempt to manipulate the UITabBar object itself stored in this property. If you attempt to do so, the tab bar view throws an exception. To configure the items for your tab bar interface, you should instead assign one or more custom view controllers to the viewControllers property. The tab bar collects the needed tab bar items from the view controllers you specify.

> The tab bar view provided by this property is only for situations where you want to display an action sheet using the showFromTabBar: method of the UIActionSheet class.
