### ISSUE TITLE
 Unable to hold your finger to close and open the controller

### ISSUE THREAD

**Issue by Terens777** [iDevelopper/PBPopupController#2]
How to open and close the popcontroller without releasing your finger from the screen? on the example of how it is implemented in LNPopupController?

**Comment by iDevelopper** [comment]
The framework tries to look like the behavior of Apple Music App. Can you elaborate?

**Comment by Terens777** [comment]
No, I should be able to clamp the panel, pull it to the top, lower it back to the bottom to the end and lift it back, not letting go while removing your finger from the screen

**Comment by Terens777** [comment]
in LNPopupController it works fine, but the other parts in your framework are more adorable

**Comment by Terens777** [comment]
https://drive.google.com/open?id=1x7z7gSOTCwzdj1Qj_XTYx7PuU_rOsBLW

**Comment by iDevelopper** [comment]
Understood with your video, I'll have a look, thanks for the other parts...

**Comment by Terens777** [comment]
Thank you, you have a great framework.

**Comment by iDevelopper** [comment]
Thank You, it's still thanks to https://github.com/LeoNatan for some parts...

**Comment by Terens777** [comment]
I can rely on your help to solve this problem in the near future, I would not want to use LNPopUp because it does not have enough functionality that I need

**Comment by iDevelopper** [comment]
Could you try with this update please? I'm not 100% sure.

```swift
            if self.isPresenting && (self.progress >= 100 || self.progress <= 0) {
                //
                if self.isPresenting || self.isDismissing {
                    self.update(self.progress >= 100 ? 100 : 0)
                }
                break;
                //
                //gesture.state = .ended
            }
```
In [PBPopupInteractivePresentationController.swift.zip](https://github.com/iDevelopper/PBPopupController/files/3113246/PBPopupInteractivePresentationController.swift.zip)

Perhaps you have to clean the build folder before to test...

**Comment by Terens777** [comment]
Your solution helped a lot, but there were problems in returning the TabBarController to its original position.  I managed to do this with
` if self.isPresenting && (self.progress >= 100 || self.progress <= 0) {
                if self.isPresenting || self.isDismissing {
                    self.update(self.progress >= 100 ? 100 : 0)
                }
            }
            
            let barHeight = self.popupController.bottomBarHeight + vc.insetsForBottomBar().bottom
            
            var barPosition: CGFloat = 0.0
          
            if progress >= 0.0 || progress <= 100 && progress >= 0.0 {
                barPosition = vc.view.frame.size.height - barHeight + (barHeight * progress)
            } else {
                barPosition = vc.view.frame.size.height - barHeight
            }`

but this decision seems to me to be wrong, please see, I would like to achieve a net result

**Comment by iDevelopper** [comment]
Finally the only thing we have to do is adjust the value of progress to 100 or 0 and let do the job:
```swift
            if self.isPresenting && (self.progress >= 100 || self.progress <= 0) {
                    self.progress = self.progress >= 100 ? 100 : 0
            }
```
[PBPopupInteractivePresentationController.swift.zip](https://github.com/iDevelopper/PBPopupController/files/3119826/PBPopupInteractivePresentationController.swift.zip)

**Comment by Terens777** [comment]
Thanks, this works perfectly for me, could you add this solution to the next release of your framework?

**Comment by iDevelopper** [comment]
Great! I will release this tomorrow or next week-end.

**Comment by Terens777** [comment]
Thanks_)

**Comment by iDevelopper** [comment]
Done!

May I ask you what is your application? Is she already on the store?

**Comment by Terens777** [comment]
Your application is still in the process of development,it will be in the store, I will inform you)
