### ISSUE TITLE
Buttons in the PopupBar do not respond when navigating back

### ISSUE THREAD

**Issue by balabon7** [iDevelopper/PBPopupController#21]
When using the PBPopupControllerSample app, I encountered one navigation issue.   
On MainTableViewController I click on a cell in the table "NavigationController"

When I move forward a few ViewControllers by clicking on the "Next" cell (pushNext) and clicking on the song cell (presentPopupBar), the PBPopupBar appears.

On this ViewController where the presentPopupBar was executed, I can interact with the playPauseAction and nextAction buttons that are located on the called PBPopupBar.

But if I navigate back a few ViewControllers in navigation, then the playPauseAction and nextAction buttons in the PBPopupBar won't call their respective methods.

If, however, if I move forward several ViewControllers (pushNext), I can interact with the playPauseAction and nextAction buttons and call the methods

Can you please tell me why this might happen?

**Comment by iDevelopper** [comment]
It must be an error in the sample code, not in the framework code. I will have a look.

**Comment by iDevelopper** [comment]
Can you provide a simple project reproducing this issue?

**Comment by balabon7** [comment]
Your repository contains a PBPopupControllerSample folder. 
I reproduced this behavior in this project - PBPopupControllerSample.xcodeproj.
Please take a look at this simple project. If you can't reproduce the error, I'll provide my simple project

**Comment by iDevelopper** [comment]
I can reproduce this behavior but I would like to have a more simple project to debug... Thanks.

**Comment by iDevelopper** [comment]
Hello, sorry for the long delay. Fixed in 3.6.6. I modified and improved the example project.

**Comment by balabon7** [comment]
Awesome. All work great. Thank you for your work, I will continue to study the library
