### ISSUE TITLE
No visual effect of Modal Page Sheet

### ISSUE THREAD

**Issue by balabon7** [iDevelopper/PBPopupController#22]
Hello Patrick. 
I implemented a project (PGPopupSample) using PBPopupController.

But when I call func presentPopupBar() and present the PopupContentViewController, then the controller below it was not animated as a stack.
(There's just an influx one on one)

<img width="322" alt="PBPopupSample" src="https://user-images.githubusercontent.com/42384032/209303504-55d8b251-cfd8-4aaf-b71c-e9cd2ddb98c8.png">

And here is how it looks in your PBPopupControllerSample application:

<img width="322" alt="PBPopupControllerSample" src="https://user-images.githubusercontent.com/42384032/209303448-d9a6d737-addd-47cb-87d4-357feb84749f.png">

I tried changing popupContentView.popupPresentationStyle but it didn't change anything in my case.

What do you think could be the reason?

Below I have provided a simple project that reproduces this issue:

https://github.com/balabon7/PBPopupSample

**Comment by iDevelopper** [comment]
Hello,

Do not set popupIgnoreDropShadowView to false. This is needed for presenting a popup after presenting a modal view as in my example.

```swift
    func commonSetup() {
        if (self.containerVC?.popupBar) != nil {
            self.containerVC.popupController.delegate = self
            if let popupContentView = self.containerVC.popupContentView {
                //popupContentView.popupIgnoreDropShadowView = false
                popupContentView.popupPresentationDuration = 0.4
                popupContentView.popupCanDismissOnPassthroughViews = true
            }
            self.collectionView?.reloadData()
        }
    }
```

**Comment by balabon7** [comment]
Thanks for the answer. This solved my problem 😊

**Comment by iDevelopper** [comment]
Welcome ! Feel free to ask.
