### ISSUE TITLE
Pod Error

### ISSUE THREAD

**Issue by swaimy** [iDevelopper/PBPopupController#25]
i am getting this error.Please help me regarding this error.

/Users/himanshu/Desktop/PBPopupControllerSample/PBPopupControllerSample.xcodeproj This Copy Files build phase contains a reference to a missing file 'PBPopupController.framework'.

**Comment by iDevelopper** [comment]
Can you explain what you did?

**Comment by swaimy** [comment]
After installation of a PBPopup pod i am getting this error

**Comment by swaimy** [comment]
Basically there is an error of pod/

**Comment by swaimy** [comment]
can you provide us latest mini player demoProject, we are implement it but now we are not able to implement it please help us.

**Comment by iDevelopper** [comment]
What do you mean by "Can you provide us latest mini player demoProject". It is on Github : https://github.com/iDevelopper/PBPopupController

You can download it, open the PBPopupControllerExample.xcworkspace and run it.
