### ISSUE TITLE
On IOS 16.5 background image appears at PBPopupBar

### ISSUE THREAD

**Issue by balabon7** [iDevelopper/PBPopupController#27]
Hello 👋

In PBPopupAudioApp I have PopupContentViewController. 
This controller has a backgroundImageView, which is positioned below the other elements.
(It serves as a background image in this controller)

When I close the PopupContentViewController with a swipe or by clicking on the PBPopupCloseButton, sometimes a part of the backgroundImageView appears in the PBPopupBar.
(This bug appears when PBPopupPresentationState.closing. Before case closed is called )

<img width="347" alt="Знімок екрана 2023-07-14 о 15 19 42" src="https://github.com/iDevelopper/PBPopupController/assets/42384032/7a232cf0-cf23-4103-a9fa-bb382a2ce10d">
<img width="341" alt="Знімок екрана 2023-07-14 о 15 20 38" src="https://github.com/iDevelopper/PBPopupController/assets/42384032/7dfc597d-3151-44d7-8abc-d448a66704bd">

This bug occurs both on a real device with iOS 16.5 and on a simulator with iOS 16.4
(I think this is an iOS 16 issue since this bug never occurred on iOS 14)
(I also tested it on a real device with IOS 14.4.2, then there are no problems)

Below I have added a screen recording video (to GoogleDrive) of how it is possible to play back:
https://drive.google.com/file/d/1JN0tvrJJkPNR5Ql9p5bmHe9RJtfjAZta/view?usp=sharing

I also noticed that on IOS 16.5, when we close the PopupContentViewController, the  blur in the PBPopupBar does not appear immediately, but approximately after PBPopupPresentationState.closed
(Perhaps this will help to understand the cause of the bug)

(On IOS 14 there is no such behavior with flickering blur in the Bar)
I also added a screen recording video (in GoogleDrive) about how it looks:
https://drive.google.com/file/d/1bOOzO-nAZo9QJz3auz2AW5Y1QpYFgGa-/view?usp=share_link

I sent you an invitation as a co-author in PBPopupAudioApp so that you can test it on a real project

Why do you think the bug might have occurred?

**Comment by iDevelopper** [comment]
Hello,

I will have a look.

However, I would have preferred a Cocoapods version as unfortunately you can’t directly edit a Swift package you add as a dependency to an Xcode project.

If I want to make changes to the Swift package for debugging purposes, I can’t.

Can you create another repository ?

Cheers,

Patrick

**Comment by balabon7** [comment]
> Hello, I will have a look. However, I would have preferred a Cocoapods version as unfortunately you can’t directly edit a Swift package you add as a dependency to an Xcode project. If I want to make changes to the Swift package for debugging purposes, I can’t. Can you create another repository ? Cheers, Patrick
> […](#)

I pushed a new version where PBPopupController is installed using the Cocoa package. 
If there's anything else I can help with, I'll be glad.

**Comment by iDevelopper** [comment]
Hello 👋,

The appearance of the popup bar depends on the appearance of the navigation controller bar & toolbar in your case.

Can you try to modify the following two functions, although I think they are useless:

In SceneDelegate.swift:

    private func setupNavigationBarBackground() {
        /*
        if #available(iOS 15, *) {
            let appearance = UINavigationBarAppearance()
            UINavigationBar.appearance().standardAppearance = appearance
            UINavigationBar.appearance().scrollEdgeAppearance = appearance
        }
        */
        if #available(iOS 13, *) {
            let navBarAppearance = UINavigationBarAppearance()
            navBarAppearance.configureWithDefaultBackground()

            let appearance = UINavigationBar.appearance()
            appearance.scrollEdgeAppearance = navBarAppearance
            appearance.compactAppearance = navBarAppearance
            appearance.standardAppearance = navBarAppearance
            if #available(iOS 15.0, *) {
                appearance.compactScrollEdgeAppearance = navBarAppearance
            }
        }
    }

In CollectionViewController.swift:

    private func setupToolbarBackground() {
        /*
        if #available(iOS 15, *) {
            let appearance = UIToolbarAppearance()
            appearance.configureWithDefaultBackground()
            UIToolbar.appearance().standardAppearance = appearance
            UIToolbar.appearance().scrollEdgeAppearance = appearance
        }
        */
        if #available(iOS 13, *) {
            let toolbarAppearance = UIToolbarAppearance()
            toolbarAppearance.configureWithDefaultBackground()
            
            navigationController!.toolbar.scrollEdgeAppearance = toolbarAppearance
            navigationController!.toolbar.compactAppearance = toolbarAppearance
            navigationController!.toolbar.standardAppearance = toolbarAppearance
            if #available(iOS 15.0, *) {
                navigationController!.toolbar.compactScrollEdgeAppearance = toolbarAppearance
            }
        }
    }

Give me some feedback.

Cheers,

Patrick
