### ISSUE TITLE
Shadow in NavigationBar during Transition on SeconVC

### ISSUE THREAD

**Issue by balabon7** [iDevelopper/PBPopupController#29]
In my project I use UINavigationController and navigate to SecondViewController using custom transition

**class PresentTransition: NSObject, UIViewControllerAnimatedTransitioning** 

While I was using version 3.6.16 Shadow in NavigationBar did not occur,

but recently I updated to a new version and this bug appeared (version 3.7.0 or higher)

<img width="833" alt="Знімок екрана 2023-11-23 о 00 10 43" src="https://github.com/iDevelopper/PBPopupController/assets/42384032/52e02bf9-08c9-4a04-a3fe-dd403ed595cb">

Could you suggest what changes were made in the navigation that could affect the behavior (which I described)?

You can see the visual behavior of the bug on the video on the disk (for 3.6.16 and 3.7.0)
https://drive.google.com/drive/folders/1u54fwfbhji9g0EDgndVxXS4zkAGZ6RO8

Here is the link to the test project
https://github.com/balabon7/PBPopupSample-5

**Comment by iDevelopper** [comment]
Hello,

An update to the framework is under development. I will take your comment into account. In the meantime you can add this test in UIView+PBPopupSupportPrivate.m:

Replace (line 56):
```objective-c
				if([groupName hasSuffix:@"🤡"] == NO)
				{
					[_self setValue:[NSString stringWithFormat:@"%@🤡", groupName] forKey:key];
				}
```
with
```objective-c
				if(groupName != nil && [groupName hasSuffix:@"🤡"] == NO)
				{
					[_self setValue:[NSString stringWithFormat:@"%@🤡", groupName] forKey:key];
				}
```
Thank you in advance for your feedback

**Comment by balabon7** [comment]
Hi,
Thank you for reacting so quickly.
I checked your change and it fixed the problem, now it works as before 👍
