### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Terens777** [iDevelopper/PBPopupController#3]
Greetings, thanks again for your work. I noticed a strange ARC behavior, after I used TabBarController with PopupBar, I make another Root controller, I have a TabBarController with all the controllers in my memory

Problems to be found in

`presentPopupBar(withPopupContentViewController: demoViewController, animated: true, completion: nil)
`

What do you advise? I am currently working on a solution

**Comment by iDevelopper** [comment]
Hi @Terens777 , I am not sure to understand.

When do you replace your root view controller and how?

Could you provide a simple example project to help?

Regards,

**Comment by Terens777** [comment]
@iDevelopper At the moment I am on a trip, on Saturday I will write you an example for clarity

**Comment by iDevelopper** [comment]
@Terens777 Good trip, Thank you.

**Comment by iDevelopper** [comment]
Hi @Terens777 , any news about this issue?

**Comment by Terens777** [comment]
@iDevelopper Due to the heavy workload I cannot provide an example, the question is still relevant, I really believe that I can update it tomorrow, thanks for your understanding and for your work.

**Comment by iDevelopper** [comment]
Hi @Terens777 , I wrote an example that may relate to your issue.

Perhaps we can discuss from this example, but for me there is no problem. Just avoid keeping strong references or destroying them.

[PBPopupLeakTest.zip](https://github.com/iDevelopper/PBPopupController/files/3243946/PBPopupLeakTest.zip)
