### ISSUE TITLE
Starting to close the popup view by sliding down but cancelling and re-opening makes the UI not register any touches

### ISSUE THREAD

**Issue by esmondmissen** [iDevelopper/PBPopupController#31]
More or less the title.

If I start to close the popupview but slide it back to the top to keep it open. Any ui element on the popup view will not receive touches anymore. You will have to close the popup and re-open it for the elements to work again

**Comment by iDevelopper** [comment]
Hello,

I manage to reproduce this behavior but I don't understand why the subviews of the popup content view no longer respond in this case. I don't see anything wrong in the view hierarchy. Only the popup close button and the pan gesture recognizer respond. Could this be an Apple bug? Do you have an idea ?

**Comment by esmondmissen** [comment]
I'm not sure sorry. I'm not super familiar with UIKit. If I with it out though I'll update any info here.

**Comment by iDevelopper** [comment]
I am not very familiar with SwiftUI, but I have noticed that it is the background of the PlayerView which is the cause when we ignore the safe area. Maybe this can help you find the solution on the SwiftUI View side. If you comment the line:

.edgesIgnoringSafeArea(.all)

It will work but the background will not cover the entire screen.

```swift
			.background({
				ZStack {
					Image(song.imageName)
						.resizable()
					BlurView()
				}
				//.edgesIgnoringSafeArea(.all)
			}())
```

**Comment by esmondmissen** [comment]
Hmm interesting. I'll have a play, it seems to be if any element is outside the safe bounds, not just the background.

**Comment by iDevelopper** [comment]
Hello,

3.9.4 Adds the `.popupContentBackground()` modifier to fixe ignoresSafeArea() displaying view out of bounds in certain circumstances (swipe down to close popup cancelled).
