### ISSUE TITLE
Scroll view gesture conflicts

### ISSUE THREAD

**Issue by salminalex** [iDevelopper/PBPopupController#4]
If add any scrollable controller as popup(table view, scroll view) gestures will conflict. I have troubles with adding UISlider to cell of table view. The solution is to activate dismissing popup swipe down gesture wile scroll view scrolled to the very top.

**Comment by iDevelopper** [comment]
This is the case. Is your scroll view embedded in a navigation controller?

**Comment by salminalex** [comment]
No, my scroll view as content view controller for pop panel.
