### ISSUE TITLE
access custom docking viewcontroller property. (help wanted)

### ISSUE THREAD

**Issue by ghimireprashant** [iDevelopper/PBPopupController#5]
how to change docking view height in run time.
how to add custom docking view in tab bar & navigation bar.
Thanks.
[https://drive.google.com/file/d/1_s5yds68pw7KRqvw8b3nEiq-Wfplb6hh/view?usp=sharing](url)

**Comment by iDevelopper** [comment]
Close by https://github.com/iDevelopper/PBPopupController/commit/288dfeba4acb68d36eb5f2a636f82255055b213c
