### ISSUE TITLE
Mysterious black bar appears over SwiftUI subviews. 

### ISSUE THREAD

**Issue by samirsd** [iDevelopper/PBPopupController#9]
Hello!

I have an app with 4 ViewControllers in a UITabbar. ViewController 1 is a regular UIKit view. No problems. The remaining ViewControllers contain SwiftUI views (making use of UIHostingController) and whenever those views come into focus, a black bar appears and grows larger with each successive appearance of that view. I tried different types of PBPopup bar / controller combinations but no luck. The black bar does not appear in the view heirerarchy debugger. Additionally this issue does not occur if you go through and view all the SwiftUI tabs. It only happens when the PBPopupController has been instantiated **before** the SwiftUI views. Any insight into this or help would be greatly appreciated. I've attached some images to aid in the description.

view 1: 
![image](https://user-images.githubusercontent.com/3209964/79676544-48e12600-81b5-11ea-9472-75cc1ee82831.png)

first appearance (the black bar appears).
![image](https://user-images.githubusercontent.com/3209964/79676577-7af28800-81b5-11ea-98d2-3dabda1ec20d.png)

end result (different tab with the same problem):
![image](https://user-images.githubusercontent.com/3209964/79676561-5eeee680-81b5-11ea-8bba-03a198379a76.png)

Best Regards,
Samir

**Comment by iDevelopper** [comment]
The framework is a little outdated from now and I plan tu update it with a new version soon. However, can you share a sample project as I don't know at all SwiftUI! Thanks.
